### ISSUE TITLE
Bitrate range for video output

### ISSUE THREAD

**Issue by xRoyBx** [iBobbyTS/VFIN#2]
What's the "-br" min/max bitrate for video output?

Using default values gives poor quality, i've tried with "-br 300M" but i get the same results/file size. Where am i doing wrong?

**Comment by iBobbyTS** [comment]
This option will be applied to FFmpeg by -b:v, ￼￼ this will be VBR(variable bit rate￼) automatically￼, max/min bit rate are controlled by FFmpeg. I'm going to change the bit rate option to CRF in the future￼ by -crf, FFmpeg will consider it as ABR(average bit rate￼)
Both VBR and ABR are more advanced than bit rate and CRF.

**Comment by iBobbyTS** [comment]
For the poor quality, I just fixed it but at the beta branch, you can replace the 1.2 branch. 
For future updates, I'll only do in to [iBobbyTS/OpenVideoEnhance](https://github.com/iBobbyTS/OpenVideoEnhance), this will include video frame interpolation, image/video super resolution, other restoration tasks like denoise, colorize and style transfer... it's not done yet, I'm working on it. 
If there are any problems for now, you can still open an issue at [VFIN](https://github.com/iBobbyTS/VFIN) or [VSR](https://github.com/iBobbyTS/VSR)

**Comment by xRoyBx** [comment]
I've tried to add/replace beta branch files into 1.2.tar and then i've used this command as always:

!/content/python/bin/python3 run.py -i "/content/drive/MyDrive/VFIN/Input_VFIN.mp4" -o "/content/drive/MyDrive/VFIN/Output_VFIN.mp4" -ot video -sf 2

but i get no output video, with this error message "At least one output file must be specified"

Thanks for your patience :)

**Comment by iBobbyTS** [comment]
Haha, all I miss is a comma at the end of line 390 in run.py. It should work now. 
By the way, you know you're using SuperSloMo, not DAIN by this command right?

**Comment by xRoyBx** [comment]
> By the way, you know you're using SuperSloMo, not DAIN by this command right?

Yes, i switch between DAIN/SSM sometimes to see how it works ;)

**Comment by xRoyBx** [comment]
Ok, now it's all right.

There still a flickering problem in the output video if i use DAIN algorythm (no problem with SSM).
I don't know if it's caused by a non-standard resolution of the input video (it's 636x360 instead of 640x360) or i need to change some other parameters in the command line, like batch size etc.

I keep trying ;)

edit: i've converted the video to regular 640x360 but when using DAIN algorythm the problem still remains

**Comment by iBobbyTS** [comment]
It should not cause any problems with that, supposed, So I gotta take a look at it. 
The model it self requires the frame height and width be divisible by 16, if not, there's a pader to expand the image and crop it afterwards. 
Anyway, I'll figure it out.

**Comment by iBobbyTS** [comment]
My testing VFIN is the [latest commit](https://github.com/iBobbyTS/VFIN/tree/990cd74e42b65ed5baa921325a894f40394fba56) from last weekend. My input video resolution is also 636x360, this is the command
`!/content/python/bin/python3.8 run.py -i "/content/test.mp4" -o /content/testo.mp4 -ot video -a DAIN`
Here are my:
[Input](https://user-images.githubusercontent.com/46138297/103532251-dbe9f980-4ec5-11eb-806b-f5f75c200483.mp4) and [Output](https://user-images.githubusercontent.com/46138297/103532260-df7d8080-4ec5-11eb-80c9-df48737a68de.mp4)
I don't see any problems, can you send me your input and output with problem to [iBobby](mailto:iBobbyTS@gmail.com)?

**Comment by xRoyBx** [comment]
Of course. I just sent them to your address with all info.
Cheers

**Comment by iBobbyTS** [comment]
I fixed it in the latest commit at beta. 
It's not caused by non-standard resolution, it's because of the DAIN model, I copied the solution from the original [Colab_Demo](https://github.com/baowenbo/DAIN/blob/master/Colab_DAIN.ipynb), A cell with "# Finding DAIN Frames, upscaling and cropping to match original".

**Comment by xRoyBx** [comment]
I've replaced your latest interpolator.py from beta branch into 1.2.tar and used the command:

!/content/python/bin/python3 run.py -i "/content/drive/MyDrive/VFIN/Input_VFIN.mp4" -o "/content/drive/MyDrive/VFIN/Output_VFIN.mp4" -ot video -a DAIN


Now i get this error message:

/content/VFIN
Traceback (most recent call last):
  File "run.py", line 337, in <module>
    intermediate_frames = interpolator.interpolate(batch[1:])
  File "/content/VFIN/DAIN/interpolator.py", line 88, in interpolate
    y_ = self.tensor2ndarray(self.model(self.torch_stack(X0, X1)))
  File "/content/VFIN/DAIN/interpolator.py", line 73, in tensor2ndarray
    item = item.permute(1, 2, 0)
RuntimeError: number of dims don't match in permute

**Comment by iBobbyTS** [comment]
Hopefully this time it will work.

**Comment by xRoyBx** [comment]
> Hopefully this time it will work.

I confirm, i've tried with different parameters (-sf, -cfr etc.) and it works.

Thanks again ;)
